#!/bin/bash
# Unified Verification Script (Linux/WSL)
# This script is the "Source of Truth" for development stability.

set -e
REPORT_FILE="E2E_TEST_REPORT.md"
START_TIME=$(date +%s)

echo "==========================================================="
echo "   MILK API MANAGER - FULL SYSTEM VERIFICATION"
echo "==========================================================="

# 1. Infrastructure Check
echo -e "
[Step 1/4] Checking Infrastructure (Docker)..."
REQUIRED_CONTAINERS=("apisix" "etcd" "prometheus" "grafana")
MISSING=()

for container in "${REQUIRED_CONTAINERS[@]}"; do
    if ! docker ps --format '{{.Names}}' | grep -q "$container"; then
        MISSING+=("$container")
    fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
    echo "   ✗ Missing: ${MISSING[*]}"
    echo "   Please run 'docker-compose up -d' first."
else
    echo "   ✓ All core infrastructure containers are running."
fi

# 2. .NET Unit Tests
echo -e "
[Step 2/4] Running .NET Unit Tests..."
if dotnet test backend/MilkApiManager.Tests/MilkApiManager.Tests.csproj --logger "console;verbosity=normal"; then
    DOTNET_STATUS="✅ OK"
    DOTNET_CODE=0
else
    DOTNET_STATUS="❌ FAIL"
    DOTNET_CODE=1
fi

# 3. Python Smoke Tests
echo -e "
[Step 3/4] Running API Smoke Tests..."
if python3 test_complete.py; then
    SMOKE_STATUS="✅ OK"
    SMOKE_CODE=0
else
    SMOKE_STATUS="❌ FAIL"
    SMOKE_CODE=1
fi

# 4. Playwright E2E Tests
echo -e "
[Step 4/4] Running Playwright E2E Tests..."
cd e2e
if npm test; then
    E2E_STATUS="✅ OK"
    E2E_CODE=0
else
    E2E_STATUS="❌ FAIL"
    E2E_CODE=1
fi
cd ..

# Generate Consolidated Report
END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))
OVERALL_STATUS="FAILED ❌"
if [ $DOTNET_CODE -eq 0 ] && [ $SMOKE_CODE -eq 0 ] && [ $E2E_CODE -eq 0 ]; then
    OVERALL_STATUS="PASSED ✅"
fi

cat <<EOF > "$REPORT_FILE"
# System Verification Report ($(date '+%Y-%m-%d %H:%M:%S'))

## Summary
- **Duration:** ${DURATION} seconds
- **Overall Status:** $OVERALL_STATUS

## Component Breakdown
| Component | Status | Details |
|-----------|--------|---------|
| .NET Backend | $DOTNET_STATUS | 48 Unit Tests |
| API Gateway | $SMOKE_STATUS | Python Smoke Test |
| Admin UI | $E2E_STATUS | Playwright E2E |

---
*Generated by OpenClaw Development Flow*
EOF

# Output to GitHub Summary if available
if [ -n "$GITHUB_STEP_SUMMARY" ]; then
    cat "$REPORT_FILE" >> "$GITHUB_STEP_SUMMARY"
fi

echo -e "
Report generated: $REPORT_FILE"
echo "==========================================================="
